var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                  xxx            ox!xx          ",
   "                                             xx                  x!!!x          ",
   "                                                                 xx!xx xx       ",
   "                                                                  xvx           ",
   "  x @               o            x                            o             xx  ",
   "  xxx                      xx            xxx                  x              x  ",
   "  x                 o                o o x                    x              x  ",
   "  x     xxx       xxxx              xxxxxx                    x            f x  ",
   "  x          xxxx           o                                    x e  y      x  ",
   "  x         xxx           xxxx                            xx     xxxxx!!!!xxxx  ",
   "  x!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!xxxxxxx   xxxxxxxxx  ",
   "  xxxxxxxxxxxxx!!!!!!!!!!xxxxxx!!!xx!!!!!!!!!!!!!!!!xx!!!!!x                    ",
   "               xxxxxxxxxx     x!!!x xxxxxx!!!!xxxxxx xxxxxxx                    ",
   "                              x!!!x       xxxx                                  ",
   "                              xxxxx                                             ",
   "                                                                                ",
   "                                                                                "],
  ["                                     !x!!xxxxxxxxxxxx            x!!!!!!!x                                   x!x  ",
   "                                     !x!!xXXXXXXXXXXX         xxxxxxxxxxxxxxx                                x!x  ",
   "                                     !x!!xxxxxxxxxxxx         x            xx                                x!x  ",
   "                                   !!!xxx!!!!!!!!!!xx                       xx                               x!x  ",
   "                      o            !!!!!!!!!!!!!!!!xx        g                                    o   o   o  x!x  ",
   "                      x  x!!!!!!!!!!!xxxxxxxxxxxxx!x         x     |   |                  g                 xx!x  ",
   "                      x   v  v v v  v            xvx         x     o   o                 xx   xxxxxxxxxxxxxxx!!x  ",
   "                xxxx  x                                      x   xxxxxxxxx   v           v!!!!!!!!!!!!!!!!!!!!xx  ",
   "                      x                                      xx  =   =   =  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                      x                                       xx!!!!!!!!!!!xx                                     ",
   "                                           o  o                xxxx!!!!!xxxx                                      ",
   "             xx                           xxxxxx                  x!xxxxxx       xxx         xxx                  ",
   "                                               x                   !     x       x x         x x                  ",
   "                                               x                   !     x         x         x                    ",
   "                                               x                   !     x         xx        x                    ",
   "                                               x                   v     x         x         x                    ",
   "                         o  o                  x            ?        x   x         x         x                    ",
   "                        xxxxxx      xxx        x                     x   x         x         x                    ",
   "                                x    x!!!!!!!!!x         xxxxxx      x   x   xxxxxxxxx       x                    ",
   "                                x o  x!!!!!!!!!x    xx               x   x   x               x                    ",
   "     @?                         x    x!!!!!!!!!x     x               xx  x   x               x                    ",
   "    xxx                       g x    x!!!!!!!!!x     x               x   xxxxx  xxxxxxx      x                    ",
   "    x x                     xxxxx o  xx!!!!!!!x      x               x           x x         x                    ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!!xx      xxxxxxxx       x!!!!!!!!!!     xf    e     x x         x                    ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!xx                      x!!!!!!!xx!     xxxxxxxxxxxxx xx      ?xx                    ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!x    o                 xx!!!!!!xx !                    xx!!!!!xx                     ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        f                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x!!                                                                   ",
   "                                       xxx!                                                                   ",
   "                                       x!x!                !!!        !!!  xxx                                ",
   "                                       x!x!!               !x!        !x!                                     ",
   "                                     xxx!xxv               x          x!!                                    ",
   "                                      x ! x                 x   oooo   x       xxx                            ",
   "                                      x ! x                 x          x      x!!!x                           ",
   "                                    xxx ! x                 xxxxxxxxxxxx       xvx                            ",
   "                                      x ! xx      x   x      x                                                ",
   "                                      x ! xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x ! x           x                    x!!!x                              ",
   "                                      x ! x           x                     xxx                               ",
   "                               xxx    x ! xx  e  x    x             o                                         ",
   "                                      x ! xxxxxxxx    x            xxx                                        ",
   "                                      x ! x           x           x!!!x                                       ",
   "                                      x ! x           x            xxx       xxx                              ",
   "                                     xx ! xx     x  e x                     x!!!x                             ",
   "                              o   o   x ! x      xxxxxx     x                xxv        xxx                   ",
   "                                      x ! x           x              x                 x!!!x                  ",
   "                              xx xxx xxx!xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xvx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxxxxxx                     x     x     x                                         x!!!x                xxx  ",
   "  x                           x    xxx    x                                          xvx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x         o        @ ?         x x x                             x  ",
   "  x                           x           x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                           x    o o    x                              x         xxx                     x  ",
   "  x                           xx    g     x                             xxx       x!!!x          x         x  ",
   "  x                           x  e xxx e  x y   e  y  y   e  y  y  e    x x        xvx          xxx        x  ",
   "  x                           xxxxxxxxxxxxx!!xxxxxx!!!!xxxxxx!!!!xxxxxxxx xx                    xxx        x  ",
   "  x         ?                 x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                           x                                                                  ",
   "            x   x    x       x  x  xxxxx   x                                                                  ",
   "            x   x    x       x  x  x   x   x                                                                  ",
   "            x   x     x  x  x   x  x   x                                                                      ",
   "             xxx       x   x    x  x   x   x                                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "       @                                                                                                      ",
   "  xxxxxxx                                                                                                     ",
   "        xxxx                                                                                                  ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
